export const icons = [
  { label: "SPA", value: "spa" },
  { label: "Fila de Espera", value: "graduation-cap" },
  { label: "Academia", value: "dumbbell" },
  { label: "Calendário", value: "calendar" },
  { label: "Futebol", value: "futbol" },
  { label: "Competição", value: "medal" },
  { label: "Favoritos", value: "heart" },
  { label: "Livro aberto", value: "book-open" },
  { label: "Corrida", value: "running" },
  { label: "Telefone", value: "phone" },
  { label: "Tênis", value: "tennis-ball" },
  { label: "Agua", value: "water" },
  { label: "Jacuzzi", value: "hot-tub" },
  { label: "Banho", value: "bath" },
  { label: "Estacionamento", value: "car-garage" },
  { label: "Acessíbilidade", value: "accessible-icon" },
  { label: "Troféu", value: "trophy" },
  { label: "Sino", value: "bell" },
  { label: "Envelope", value: "envelope" },
  { label: "Medicina", value: "user-md" },
];
