name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  NODE_VERSION: '18.x'   
  API_BASE_URL: https://teste-backend-backoffice-laravel.azurewebsites.net/api/v2
  API_BASE_URL_SCHEDULE: https://testeappbackendlaravel.azurewebsites.net/api/v2
  API_KEY: xOuWgoB1D9suLlfiey63mvsqKgobS/DfLLMQtIjDUhw=
  IS_DEMO: 1
  FIREBASE_API_KEY: "AIzaSyA74uIIlpIEZMRgb1L7X7fERxuN4G0gH9o"
  FIREBASE_AUTH_DOMAIN: "xappa-app-abacd.firebaseapp.com"
  FIREBASE_PROJECT_ID: "xappa-app-abacd"
  FIREBASE_STORAGE_BUCKET: "xappa-app-abacd.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "444252963533"
  FIREBASE_APP_ID: "1:444252963533:web:2dd7fd4fb99eff14f81f84"
  FIREBASE_MEASUREMENT_ID: "G-4HEXK1BHVF"
  
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MEADOW_078C01A0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: ".output/server" # Api source code path - optional
          output_location: ".output/public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MEADOW_078C01A0F }}
          action: "close"
